
name: Render R Markdown to HTML

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1

    - name: Install R packages
      run: |
        R -e 'install.packages(c("rmarkdown", "knitr"))'

    - name: Render R Markdown to HTML
      run: R -e 'rmarkdown::render("github.com/amiraparker/Stats-Group-Project/Group Project.Rmd")'

    - name: Commit HTML output
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add path/to/your/RMarkdownFile.html
        git commit -m "Update HTML output"
        git push origin main
